name: Rust

on:
  push:
    branches: [ master ]
    paths:
      - 'server/src/**.rs'
env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Cargo Target Cache
      uses: actions/cache@v1
      with:
        path: ./server/target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargo-target
    - name: Modify files
      run: cd server/src && ./prep_deploy.sh
    - name: Compile
      run: cd server && cargo build --target=x86_64-unknown-linux-gnu --release
    - name: Undo modifications
      run: cd server/src && ./end_deploy.sh
    - name: show status
      run: git status
    - name: add the changes
      run: git add -f server/target/x86_64-unknown-linux-gnu
    - name: auth
      run: git config --global user.email "hwymonkey@gmail.com" && git config --global user.name "tweoss"
    - name: commit
      run: git commit -m "Compiling server for deploy"
    - name: set up auth
      run: git remote set-url --push origin https://tweoss:$GITHUB_TOKEN@github.com/tweoss/econ
    - name: push
      run: git push -f origin